_ranking_game:
  resource: "@ClubRankingBundle/Controller/GameController.php"
  type: annotation
  prefix: /ranking/game

_admin_ranking_game:
  resource: "@ClubRankingBundle/Controller/AdminGameController.php"
  type: annotation
  prefix: /admin/ranking/game
