_ranking_game:
  resource: "@ClubRankingBundle/Controller/GameController.php"
  type: annotation
  prefix: /ranking/game

_ranking_match:
  resource: "@ClubRankingBundle/Controller/MatchController.php"
  type: annotation
  prefix: /ranking/match

_ranking_match_comment:
  resource: "@ClubRankingBundle/Controller/MatchCommentController.php"
  type: annotation
  prefix: /ranking/match/comment

_admin_ranking_game:
  resource: "@ClubRankingBundle/Controller/AdminGameController.php"
  type: annotation
  prefix: /admin/ranking/game

_admin_ranking_rule:
  resource: "@ClubRankingBundle/Controller/AdminRuleController.php"
  type: annotation
  prefix: /admin/ranking/rule
