services:
  club.welcomebundle.left_menu_listener:
    class: Club\WelcomeBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: left_menu.render, method: onLeftMenuRender }
