services:
  club.welcomebundle.top_menu_listener:
    class: Club\WelcomeBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: top_menu.render, method: onTopMenuRender }

