_welcome:
  resource: "@ClubWelcomeBundle/Controller/WelcomeController.php"
  type: annotation

_blog:
  resource: "@ClubWelcomeBundle/Controller/BlogController.php"
  type: annotation

_admin_blog:
  resource: "@ClubWelcomeBundle/Controller/AdminBlogController.php"
  type: annotation
  prefix: /admin

_admin_welcome:
  resource: "@ClubWelcomeBundle/Controller/AdminWelcomeController.php"
  type: annotation
  prefix: /admin

