services:
  club.bookingbundle.left_menu_listener:
    class: Club\BookingBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator, %club_booking.enabled%]
    tags:
      - { name: kernel.event_listener, event: left_menu.render, method: onLeftMenuRender }
  club.bookingbundle.top_menu_listener:
    class: Club\BookingBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator, %club_booking.enabled%]
    tags:
      - { name: kernel.event_listener, event: top_menu.render, method: onTopMenuRender }
  club.bookingbundle.dashboard_listener:
    class: Club\BookingBundle\Listener\DashboardListener
    arguments: [@doctrine.orm.entity_manager, @security.context, @templating]
    tags:
      - { name: kernel.event_listener, event: dashboard.view, method: onDashboardView }
