_admin_field:
  resource: "@ClubBookingBundle/Controller/AdminFieldController.php"
  type: annotation
  prefix: /admin

_admin_plan:
  resource: "@ClubBookingBundle/Controller/AdminPlanController.php"
  type: annotation
  prefix: /admin/booking/plan

_admin_interval:
  resource: "@ClubBookingBundle/Controller/AdminIntervalController.php"
  type: annotation
  prefix: /admin

_booking:
  resource: "@ClubBookingBundle/Controller/BookingController.php"
  type: annotation

_location:
  resource: "@ClubBookingBundle/Controller/LocationController.php"
  type: annotation
  prefix: /booking

_overview:
  resource: "@ClubBookingBundle/Controller/OverviewController.php"
  type: annotation
