_admin_field:
  resource: "@ClubBookingBundle/Controller/AdminFieldController.php"
  type: annotation
  prefix: /admin

_admin_plan_category:
  resource: "@ClubBookingBundle/Controller/AdminPlanCategoryController.php"
  type: annotation
  prefix: /admin/booking/plan_category

_admin_plan:
  resource: "@ClubBookingBundle/Controller/AdminPlanController.php"
  type: annotation
  prefix: /admin/booking/plan

_admin_interval:
  resource: "@ClubBookingBundle/Controller/AdminIntervalController.php"
  type: annotation
  prefix: /admin

_booking:
  resource: "@ClubBookingBundle/Controller/BookingController.php"
  type: annotation

_overview:
  resource: "@ClubBookingBundle/Controller/OverviewController.php"
  type: annotation
