services:
  club.eventbundle.listener.left_menu_render_listener:
    class: Club\EventBundle\Listener\LeftMenuRenderListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: left_menu.render, method: onLeftMenuRender }
