_match_league:
  resource: "@ClubMatchBundle/Controller/LeagueController.php"
  type: annotation
  prefix: /match/league

_match_match:
  resource: "@ClubMatchBundle/Controller/MatchController.php"
  type: annotation
  prefix: /match/match

_match_match_comment:
  resource: "@ClubMatchBundle/Controller/MatchCommentController.php"
  type: annotation
  prefix: /match/match/comment

_admin_match_league:
  resource: "@ClubMatchBundle/Controller/AdminLeagueController.php"
  type: annotation
  prefix: /admin/match/league

_admin_match_rule:
  resource: "@ClubMatchBundle/Controller/AdminRuleController.php"
  type: annotation
  prefix: /admin/match/rule
