services:
    club_match.match:
        class: Club\MatchBundle\Helper\Match
        arguments: [@doctrine.orm.entity_manager, @translator]
    club_match.league:
        class: Club\MatchBundle\Helper\League
        arguments: [@doctrine.orm.entity_manager, @translator]
