services:
  club.mailbundle.listener.on_password_reset_listener:
    class: Club\MailBundle\Listener\PasswordResetListener
    arguments: [@doctrine.orm.entity_manager, @templating, @router, @clubmaster_mailer]
    tags:
      - { name: kernel.event_listener, event: password.reset, method: onPasswordReset }
  club.mailbundle.listener.on_user_new_listener:
    class: Club\MailBundle\Listener\UserNewListener
    arguments: [@doctrine.orm.entity_manager, @templating, @router, @clubmaster_mailer]
    tags:
      - { name: kernel.event_listener, event: user.new, method: onUserNew }
  club.mailbundle.listener.on_order_new_listener:
    class: Club\MailBundle\Listener\OrderNewListener
    arguments: [@doctrine.orm.entity_manager, @templating, @router, @clubmaster_mailer]
    tags:
      - { name: kernel.event_listener, event: shop.order, method: onShopOrder }
  club.mailbundle.listener.on_mail_task_listener:
    class: Club\MailBundle\Listener\MailSendListener
    arguments: [@doctrine.orm.entity_manager, @mailer, @swiftmailer.transport.real]
    tags:
      - { name: kernel.event_listener, event: mail.task, method: onMailTask }
