services:
  swift_reporter:
    class: Club\MailBundle\Helper\SwiftReporter
    arguments: [@doctrine.orm.entity_manager]
  order:
    class: Club\ShopBundle\Helper\Order
    arguments: [@doctrine.orm.entity_manager,@event_dispatcher]
  subscription:
    class: Club\ShopBundle\Helper\Subscription
    arguments: [@doctrine.orm.entity_manager,@session,@translator]
  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }
