Club\UserBundle\Entity\User:
  type: entity
  table: club_user
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    profile_id: { type: integer, nullable: false }
    username: { type: string(255), nullable: false }
    password: { type: string(255) }
    language_id: { type: string(255) }
    last_login_time: { type: date }
    last_login_ip: { type: string, string: '100' }
  oneToOne:
    profile:
      targetEntity: Club\UserBundle\Entity\Profile
      joinColumns:
        profile_id:
          referencedColumnName: id
  lifecycleCallbacks: {  }
