Club\UserBundle\Entity\Profile:
  type: entity
  table: club_profile
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    first_name: { type: string(255), nullable: true }
    last_name: { type: string(255), nullable: true }
  oneToOne:
    user:
      targetEntity: User
      joinColumn:
        name: user_id
        referencedColumnName: id
        onDelete: cascade
  lifecycleCallbacks: {  }
