Club\UserBundle\Entity\Location:
  type: entity
  table: club_location
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    location_name: { type: string(255), nullable: false }
  lifecycleCallbacks: {  }
