Club\UserBundle\Entity\User:
  type: entity
  table: club_user
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    username: { type: string(255) }
    password: { type: string(255) }
    language_id: { type: string(255), nullable: true }
    last_login_time: { type: date, nullable: true }
    last_login_ip: { type: string, string: '100', nullable: true }
    created_at: { type: date, nullable: true }
    updated_at: { type: date, nullable: true }
  oneToOne:
    profile:
      targetEntity: Club\UserBundle\Entity\Profile
      cascade: [remove]
      joinColumn:
        name: profile_id
        referencedColumnName: id
  lifecycleCallbacks: {  }
