Club\UserBundle\Entity\Group:
  type: entity
  table: club_group
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    group_name: { type: string, lenght: 255, nullable: false }
    group_type: { type: string, length: 255, nullable: false }
    sex: { type: string, length: 255, nullable: true }
    min_age: { type: integer, nullable: true }
    max_age: { type: integer, nullable: true }
    is_active: { type: boolean, nullable: false, default: true }
  lifecycleCallbacks: {  }
