Club\UserBundle\Entity\ProfileEmail:
  type: entity
  table: club_profile_email
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    email_address: { type: string(255), nullable: false }
    contact_type: { type: string(20), nullable: false }
    is_default: { type: boolean, nullable: false }
  manyToOne:
    profile:
      targetEntity: Profile
  lifecycleCallbacks: {  }
