Club\UserBundle\Entity\Language:
  type: entity
  table: club_language
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name: { type: string }
    code: { type: string }
    locale: { type: string }
    charset: { type: string }
    date_format_short: { type: string }
    date_format_long: { type: string }
    time_format: { type: string }
    text_direction: { type: string }
    numeric_separator_decimal: { type: string }
    numeric_separator_thousands: { type: string }
  manyToOne:
    currency:
      targetEntity: Currency
  lifecycleCallbacks: {  }
