Club\UserBundle\Entity\Role:
  type: entity
  table: club_role
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    role_name:
      type: string
      length: '255'
      nullable: false
  lifecycleCallbacks: {  }
