Club\UserBundle\Entity\LoginAttempt:
  type: entity
  table: club_login_attempt
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    username: { type: string(255) }
    session: { type: string(255) }
    ip_address: { type: string(100), nullable: false }
    hostname: { type: string(100) }
    login_failed: { type: boolean, nullable: false }
  manyToOne:
    user:
      targetEntity: User
  lifecycleCallbacks: {  }
