Club\UserBundle\Entity\ProfilePhone:
  type: entity
  table: club_profile_phone
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    number: { type: string(100), nullable: false }
    contact_type: { type: string(20), nullable: false }
    is_default: { type: boolean, nullable: false }
  manyToOne:
    profile:
      targetEntity: Profile
  lifecycleCallbacks: {  }
