parameters:
    web_path: %kernel.root_dir%/../web
    upload_path: uploads

club_api:
    api_key: THIS_IS_A_DEMO_KEY

club_team:
    future_occurs: 25
    minutes_before_schedule: 120
    penalty_enabled: true
