parameters:
    web_path: %kernel.root_dir%/../web
    upload_path: uploads

club_payment_cash:
    enabled: true

club_payment_quickpay:
    enabled: true
    merchant: example
    secret: xxxxx
    protocol: 4
    language: en
    currency: DKK
    autocapture: 1
    cardtypelock:
    quickpay_url: https://secure.quickpay.dk/form/

club_api:
    api_key: THIS_IS_A_DEMO_KEY

club_event:
    enabled: true

club_ranking:
    enabled: true

club_team:
    enabled: true
    future_occurs: 14
    minutes_before_schedule: 120
    penalty_enabled: true
    cancel_minute_before: 120
    cancel_minute_created: 5
    num_team_day: 1
    num_team_future: 4
    penalty_product_name: 'Penalty for missed team'

club_booking:
    enabled: true
    enable_guest: true
    num_book_guest_day: 1
    num_book_guest_future: 1
    num_book_same_partner_day: 1
    num_book_same_partner_future: 1
    num_book_day: 1
    num_book_future: 4
    cancel_minute_before: 120
    cancel_minute_created: 5
    booking_style: horizontal

club_mail:
    default_sender_address: info@clubmaster.org
    default_sender_name: ClubMaster Administrator

ornicar_gravatar:
    rating: g
    size: 160
    default: mm
