homepage:
  pattern: /
  defaults: { _controller: ClubWelcomeBundle:Welcome:index }

_api:
  resource: "@ClubAPIBundle/Resources/config/routing.yml"

_team:
  resource: "@ClubTeamBundle/Resources/config/routing.yml"

_shop:
  resource: "@ClubShopBundle/Resources/config/routing.yml"

_user:
  resource: "@ClubUserBundle/Resources/config/routing.yml"

_task:
  resource: "@ClubTaskBundle/Resources/config/routing.yml"

_mail:
  resource: "@ClubMailBundle/Resources/config/routing.yml"

_log:
  resource: "@ClubLogBundle/Resources/config/routing.yml"

_event:
  resource: "@ClubEventBundle/Resources/config/routing.yml"

_installer:
  resource: "@ClubInstallerBundle/Resources/config/routing.yml"
  prefix: /installer

_configurator:
  resource: "@ClubConfiguratorBundle/Resources/config/routing/webconfigurator.xml"
  prefix: /configurator

_message:
  resource: "@ClubMessageBundle/Resources/config/routing.yml"

_booking:
  resource: "@ClubBookingBundle/Resources/config/routing.yml"

_dashboard:
  resource: "@ClubDashboardBundle/Resources/config/routing.yml"

_welcome:
  resource: "@ClubWelcomeBundle/Resources/config/routing.yml"

_feedback:
  resource: "@ClubFeedbackBundle/Resources/config/routing.yml"
