homepage:
  pattern: /
  defaults: { _controller: ClubUser:User:index }

user:
  resource: "@ClubUser/Resources/config/routing.yml"

_user:
  resource: "@ClubUser/Controller/UserController.php"
  type: annotation
