ClubTournamentBundle:
    resource: "@ClubTournamentBundle/Controller/"
    type:     annotation
    prefix:   /

ClubRequestBundle:
    resource: "@ClubRequestBundle/Controller/"
    type:     annotation
    prefix:   /

ClubNewsBundle:
    resource: "@ClubNewsBundle/Controller/"
    type:     annotation
    prefix:   /

ClubPasskeyBundle:
    resource: "@ClubPasskeyBundle/Controller/"
    type:     annotation

ClubCheckinBundle:
    resource: "@ClubCheckinBundle/Controller/"
    type:     annotation

ClubPaymentCashBundle:
    resource: "@ClubPaymentCashBundle/Controller/"
    type:     annotation
    prefix:   /payment/

ClubPaymentQuickpayBundle:
    resource: "@ClubPaymentQuickpayBundle/Controller/"
    type:     annotation
    prefix:   /payment/

ClubAPIBundle:
    resource: "@ClubAPIBundle/Controller/"
    type: annotation
    prefix: /api/

ClubTeamBundle:
    resource: "@ClubTeamBundle/Controller/"
    type: annotation

ClubShopBundle:
    resource: "@ClubShopBundle/Controller/"
    type: annotation

ClubUserBundle:
    resource: "@ClubUserBundle/Controller/"
    type: annotation

ClubTaskBundle:
    resource: "@ClubTaskBundle/Controller/"
    type:     annotation

ClubMailBundle:
    resource: "@ClubMailBundle/Controller/"

ClubLogBundle:
    resource: "@ClubLogBundle/Controller/"
    type:     annotation

ClubEventBundle:
    resource: "@ClubEventBundle/Controller/"
    type:     annotation

ClubInstallBundle:
    resource: "@ClubInstallerBundle/Controller/"
    prefix:   /installer
    type:     annotation

ClubConfiguratorBundle:
    resource: "@ClubConfiguratorBundle/Controller/"
    type:     annotation

ClubMessageBundle:
    resource: "@ClubMessageBundle/Controller/"
    type:     annotation

ClubBookingBundle:
    resource: "@ClubBookingBundle/Controller/"
    type:     annotation

ClubDashboardBundle:
    resource: "@ClubDashboardBundle/Controller/"
    type:     annotation

ClubWelcomeBundle:
    resource: "@ClubWelcomeBundle/Controller/"
    type:     annotation

ClubFeedbackBundle:
    resource: "@ClubFeedbackBundle/Controller/"

ClubMatchBundle:
    resource: "@ClubMatchBundle/Controller/"

homepage:
    pattern: /
    defaults: { _controller: ClubWelcomeBundle:Welcome:index }
