_security_login:
    pattern:  /login
    defaults: { _controller: ClubUser:Auth:login }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

homepage:
  pattern: /
  defaults: { _controller: ClubUser:User:index }

_user:
  resource: "@ClubUser/Controller/UserController.php"
  type: annotation

_group:
  resource: "@ClubUser/Controller/GroupController.php"
  type: annotation

_location:
  resource: "@ClubUser/Controller/LocationController.php"
  type: annotation

_role:
  resource: "@ClubUser/Controller/RoleController.php"
  type: annotation

_auth:
  resource: "@ClubUser/Controller/AuthController.php"
  type: annotation

