homepage:
  pattern: /
  defaults: { _controller: ClubUserBundle:User:index }

_shop:
  resource: "@ClubShopBundle/Resources/config/routing.yml"

_user:
  resource: "@ClubUserBundle/Resources/config/routing.yml"

_rest:
  resource: "@ClubRestBundle/Resources/config/routing.yml"
