security:
    encoders:
        Club\UserBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_BLOG_ADMIN,ROLE_BOOKING_ADMIN,ROLE_EVENT_ADMIN,ROLE_MEMBER_ADMIN,ROLE_MESSAGE_ADMIN,ROLE_MATCH_ADMIN,ROLE_SHOP_ADMIN,ROLE_TEAM_ADMIN, ROLE_PASSKEY_ADMIN, ROLE_TOURNAMENT_ADMIN, ROLE_NEWS_ADMIN]

    providers:
        main:
            entity: { class: Club\UserBundle\Entity\User, property: member_number }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        api:
            pattern: ^/api
            anonymous: ~
            http_basic:
                realm: "ClubMaster API"

        user:
            pattern: ^/
            anonymous: ~
            form_login:
                failure_handler: failure.password.handler
                check_path: /login_check
                login_path: /login
                default_target_path: /user/dashboard
            logout:
                path: /logout

    access_control:
        - { path: ^/admin/booking, roles: ROLE_BOOKING_ADMIN }
        - { path: ^/admin/event, roles: ROLE_EVENT_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
