services:
  club.installer.listener.redirect:
    class: Club\InstallerBundle\Listener\Redirect
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
