services:
  club.payment.quickpay.listener:
    class: Club\Payment\QuickpayBundle\Listener\Quickpay
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: paymentmethod.get, method: onPaymentMethodGet }
