Club\MailBundle\Entity\MailQueue:
  type: entity
  table: club_mail_queue
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    message: { type: text }
    error_message: { type: string }
    priority: { type: integer }
  lifecycleCallbacks: {  }
