parameters:
#    club_menu.example.class: Club\MenuBundle\Example

services:
#    club_menu.example:
#        class: %club_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
