services:
  club.payment.cash.listener:
    class: Club\Payment\CashBundle\Listener\Cash
    arguments: [@service_container]
    tags:
      - { name: kernel.event_listener, event: paymentmethod.get, method: onPaymentMethodGet }
