services:
  club.feedback.listener.menu:
    class: Club\FeedbackBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: top_right_menu.render, method: onTopRightMenuRender }
