services:
  club.taskbundle.listener.task:
    class: Club\TaskBundle\Listener\TaskListener
    arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @logger]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
  club.task.fixtures.load:
    class: Club\TaskBundle\Fixtures\Load
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.event_listener, event: fixtures.init, method: onFixturesInit }
