Club\ShopBundle\Entity\TicketCoupon:
  type: entity
  table: club_ticket_coupon
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    tickets: { type: integer }
    start_date: { type: datetime }
    expire_date: { type: datetime }
  manyToOne:
    user:
      targetEntity: Club\UserBundle\Entity\User
  lifecycleCallbacks: {  }
