Club\ShopBundle\Entity\ShopImage:
  type: entity
  table: club_shop_image
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    file_path: { type: string }
    file_name: { type: string }
    file_type: { type: string }
    file_size: { type: string }
    file_hash: { type: string }
  lifecycleCallbacks: {  }
