Club\ShopBundle\Entity\ShopOrderItem:
  type: entity
  table: club_shop_order_item
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    quantity: { type: integer }
    price: { type: float }
    tax: { type: float }
    name: { type: string }
    model: { type: string }
  manyToOne:
    shop_order:
      targetEntity: ShopOrder
  manyToOne:
    shop_product:
      targetEntity: ShopProduct
  lifecycleCallbacks: {  }
