Club\ShopBundle\Entity\Subscription:
  type: entity
  table: club_subscription
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    start_date: { type: datetime }
    expire_date: { type: datetime }
    allowed_pauses: { type: integer }
    auto_renewal: { type: boolean }
  manyToMany:
    users:
      targetEntity: Club\UserBundle\Entity\User
  lifecycleCallbacks: {  }
