Club\ShopBundle\Entity\ShopProduct:
  type: entity
  table: club_shop_product
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    product_name: { type: string }
    description: { type: text }
    price: { type: float }
    quantity: { type: integer }
  manyToMany:
    shop_categories:
      targetEntity: ShopCategory
  manyToMany:
    shop_values:
      targetEntity: ShopValue
  manyToMany:
    roles:
      targetEntity: Club\UserBundle\Entity\Role
  lifecycleCallbacks: {  }
