Club\ShopBundle\Entity\ShopSpecial:
  type: entity
  table: club_shop_special
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    start_date: { type: datetime }
    expire_date: { type: datetime }
    price: { type: float }
  manyToOne:
    shop_product:
      targetEntity: ShopProduct
  lifecycleCallbacks: {  }
