Club\ShopBundle\Entity\ShopValue:
  type: entity
  table: club_shop_value
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    product_key: { type: string }
    product_value: { type: string }
  manyToMany:
    shop_product:
      targetEntity: ShopProduct
  lifecycleCallbacks: {  }
