Club\ShopBundle\Entity\ShopCart:
  type: entity
  table: club_shop_cart
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    quantity: { type: integer }
    session: { type: string }
  manyToOne:
    product:
      targetEntity: ShopProduct
  lifecycleCallbacks: {  }
