Club\ShopBundle\Entity\ShopShipping:
  type: entity
  table: club_shop_shipping
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    shipping_name: { type: string }
    description: { type: text }
    price: { type: float }
  lifecycleCallbacks: {  }
