services:
  cart:
    class: Club\ShopBundle\Helper\Cart
    arguments: [@doctrine.orm.entity_manager,@session,@security.context]
  order:
    class: Club\ShopBundle\Helper\Order
    arguments: [@doctrine.orm.entity_manager,@event_dispatcher]
  subscription:
    class: Club\ShopBundle\Helper\Subscription
    arguments: [@doctrine.orm.entity_manager,@session,@translator]
