services:
  club.shopbundle.listener.order:
    class: Club\ShopBundle\Listener\ChangeOrderStatusListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.listener, event: onShopOrder }

