services:
  club.shopbundle.listener.on_shop_order_listener:
    class: Club\ShopBundle\Listener\NewOrderListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
      - { name: kernel.listener, event: onShopOrder }
