_shop:
  resource: "@ClubShopBundle/Controller/ShopController.php"
  type: annotation

_shop_category:
  resource: "@ClubShopBundle/Controller/CategoryController.php"
  type: annotation

_shop_product:
  resource: "@ClubShopBundle/Controller/ProductController.php"
  type: annotation

_shop_checkout:
  resource: "@ClubShopBundle/Controller/CheckoutController.php"
  type: annotation

_shop_order:
  resource: "@ClubShopBundle/Controller/OrderController.php"
  type: annotation

_shop_subscription:
  resource: "@ClubShopBundle/Controller/SubscriptionController.php"
  type: annotation

_shop_coupon:
  resource: "@ClubShopBundle/Controller/CouponController.php"
  type: annotation

_admin_shop_special:
  resource: "@ClubShopBundle/Controller/AdminSpecialController.php"
  type: annotation
  prefix: /admin

_admin_shop_subscription:
  resource: "@ClubShopBundle/Controller/AdminSubscriptionController.php"
  type: annotation
  prefix: /admin

_admin_shop_coupon:
  resource: "@ClubShopBundle/Controller/AdminCouponController.php"
  type: annotation
  prefix: /admin

_admin_shop_product:
  resource: "@ClubShopBundle/Controller/AdminProductController.php"
  type: annotation
  prefix: /admin

_admin_shop_product_attribute:
  resource: "@ClubShopBundle/Controller/AdminProductAttributeController.php"
  type: annotation
  prefix: /admin

_admin_shop_category:
  resource: "@ClubShopBundle/Controller/AdminCategoryController.php"
  type: annotation
  prefix: /admin

_admin_shop_order:
  resource: "@ClubShopBundle/Controller/AdminOrderController.php"
  type: annotation
  prefix: /admin

_admin_shop_order_filter:
  resource: "@ClubShopBundle/Controller/AdminOrderFilterController.php"
  type: annotation
  prefix: /admin

_admin_shop_payment_method:
  resource: "@ClubShopBundle/Controller/AdminPaymentMethodController.php"
  type: annotation
  prefix: /admin

_admin_shop_shipping:
  resource: "@ClubShopBundle/Controller/AdminShippingController.php"
  type: annotation
  prefix: /admin

_admin_shop_vat:
  resource: "@ClubShopBundle/Controller/AdminVatController.php"
  type: annotation
  prefix: /admin
