services:
    club.apibundle.listener.response:
        class: Club\APIBundle\Listener\ResponseListener
        arguments: [@request_stack]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: OnKernelResponse }
