_api_auth:
  resource: "@ClubAPIBundle/Controller/AuthController.php"
  type: annotation
  prefix: /api

_api_event:
  resource: "@ClubAPIBundle/Controller/EventController.php"
  type: annotation
  prefix: /api/event

