_api_auth:
  resource: "@ClubAPIBundle/Controller/AuthController.php"
  type: annotation
  prefix: /api

_api_event:
  resource: "@ClubAPIBundle/Controller/EventController.php"
  type: annotation
  prefix: /api/events

_api_team:
  resource: "@ClubAPIBundle/Controller/TeamController.php"
  type: annotation
  prefix: /api/teams

_api_user:
  resource: "@ClubAPIBundle/Controller/UserController.php"
  type: annotation
  prefix: /api/users

