parameters:
#    club_api.example.class: Club\APIBundle\Example

services:
#    club_api.example:
#        class: %club_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
