parameters:
#    club_communication.example.class: Club\CommunicationBundle\Example

services:
#    club_communication.example:
#        class: %club_communication.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
