services:
  club_user_extension_price:
    class: Club\UserBundle\Twig\Extension\PriceExtension
    arguments: [@doctrine.orm.entity_manager, @security.context, @session]
    tags:
      - { name: twig.extension }
