services:
  club_layout_extension_price:
    class: Club\LayoutBundle\Twig\Extension\PriceExtension
    arguments: [@doctrine.orm.entity_manager, @security.context, @session]
    tags:
      - { name: twig.extension }
