services:
  club.accountbundle.listener.on_shop_order_listener:
    class: Club\AccountBundle\Listener\NewTransactionListener
    arguments: [@doctrine.orm.entity_manager,@security.context]
    tags:
      - { name: kernel.listener, event: shop.order, method: onShopOrder }
