services:
  failure.password.handler:
    class: Club\UserBundle\Helper\FailurePasswordHandler
    arguments: [@doctrine.orm.entity_manager]
  clubmaster.version:
    class: Club\UserBundle\Helper\Version
  clubmaster.ban:
    class: Club\UserBundle\Helper\Ban
    arguments: [@doctrine.orm.entity_manager, @security.context]
  clubmaster.user:
    class: Club\UserBundle\Helper\User
    arguments: [@service_container]
  club_user.reset_password:
    class: Club\UserBundle\Helper\ResetPassword
    arguments: [@doctrine.orm.entity_manager]
