services:
  clubmaster.twig.extension:
    class: Club\UserBundle\Extension\PriceExtension
    arguments: [@doctrine.orm.entity_manager, @security.context, @session]
    tags:
      - { name: twig.extension }
