services:
  club.teambundle.left_menu_listener:
    class: Club\TeamBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: left_menu.render, method: onLeftMenuRender }
  club.teambundle.top_menu_listener:
    class: Club\TeamBundle\Listener\MenuListener
    arguments: [@router, @security.context, @translator]
    tags:
      - { name: kernel.event_listener, event: top_menu.render, method: onTopMenuRender }
  club.team.repetition.change:
    class: Club\TeamBundle\Listener\GenerateScheduleListener
    arguments: [@doctrine.orm.entity_manager, %club_team.future_occurs%]
    tags:
      - { name: kernel.event_listener, event: repetition.change, method: onRepetitionChange }
  club.team.team.task:
    class: Club\TeamBundle\Listener\GenerateScheduleListener
    arguments: [@doctrine.orm.entity_manager, %club_team.future_occurs%]
    tags:
      - { name: kernel.event_listener, event: team.task, method: onTeamTask }
  club.team.team.penalty:
    class: Club\TeamBundle\Listener\TeamPenaltyListener
    arguments: [@doctrine.orm.entity_manager, %club_team.minutes_before_schedule%, %club_team.penalty_enabled%, @order]
    tags:
      - { name: kernel.event_listener, event: team.penalty, method: onTeamPenalty }
