_team:
  resource: "@ClubTeamBundle/Controller/TeamController.php"
  type: annotation

_admin_level:
  resource: "@ClubTeamBundle/Controller/AdminLevelController.php"
  type: annotation
  prefix: /admin

_admin_team_category:
  resource: "@ClubTeamBundle/Controller/AdminTeamCategoryController.php"
  type: annotation
  prefix: /admin/team/category

_admin_schedule:
  resource: "@ClubTeamBundle/Controller/AdminScheduleController.php"
  type: annotation
  prefix: /admin

_admin_repetition:
  resource: "@ClubTeamBundle/Controller/AdminRepetitionController.php"
  type: annotation
  prefix: /admin
