_team:
  resource: "@ClubTeamBundle/Controller/TeamController.php"
  type: annotation

_admin_participant:
  resource: "@ClubTeamBundle/Controller/AdminParticipantController.php"
  type: annotation
  prefix: /admin

_admin_level:
  resource: "@ClubTeamBundle/Controller/AdminLevelController.php"
  type: annotation
  prefix: /admin

_admin_team_category:
  resource: "@ClubTeamBundle/Controller/AdminTeamCategoryController.php"
  type: annotation
  prefix: /admin/team/category

_admin_team:
  resource: "@ClubTeamBundle/Controller/AdminTeamController.php"
  type: annotation
  prefix: /admin/team/team

_admin_repetition:
  resource: "@ClubTeamBundle/Controller/AdminRepetitionController.php"
  type: annotation
  prefix: /admin
